/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CrudSummaryRouteImport } from './routes/crud.summary'
import { Route as CrudSearchRouteImport } from './routes/crud.search'
import { Route as CrudIdRouteImport } from './routes/crud.$id'

const CrudSummaryRoute = CrudSummaryRouteImport.update({
  id: '/crud/summary',
  path: '/crud/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const CrudSearchRoute = CrudSearchRouteImport.update({
  id: '/crud/search',
  path: '/crud/search',
  getParentRoute: () => rootRouteImport,
} as any)
const CrudIdRoute = CrudIdRouteImport.update({
  id: '/crud/$id',
  path: '/crud/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/crud/$id': typeof CrudIdRoute
  '/crud/search': typeof CrudSearchRoute
  '/crud/summary': typeof CrudSummaryRoute
}
export interface FileRoutesByTo {
  '/crud/$id': typeof CrudIdRoute
  '/crud/search': typeof CrudSearchRoute
  '/crud/summary': typeof CrudSummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/crud/$id': typeof CrudIdRoute
  '/crud/search': typeof CrudSearchRoute
  '/crud/summary': typeof CrudSummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/crud/$id' | '/crud/search' | '/crud/summary'
  fileRoutesByTo: FileRoutesByTo
  to: '/crud/$id' | '/crud/search' | '/crud/summary'
  id: '__root__' | '/crud/$id' | '/crud/search' | '/crud/summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CrudIdRoute: typeof CrudIdRoute
  CrudSearchRoute: typeof CrudSearchRoute
  CrudSummaryRoute: typeof CrudSummaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/crud/summary': {
      id: '/crud/summary'
      path: '/crud/summary'
      fullPath: '/crud/summary'
      preLoaderRoute: typeof CrudSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crud/search': {
      id: '/crud/search'
      path: '/crud/search'
      fullPath: '/crud/search'
      preLoaderRoute: typeof CrudSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crud/$id': {
      id: '/crud/$id'
      path: '/crud/$id'
      fullPath: '/crud/$id'
      preLoaderRoute: typeof CrudIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  CrudIdRoute: CrudIdRoute,
  CrudSearchRoute: CrudSearchRoute,
  CrudSummaryRoute: CrudSummaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
