output-dir: '{project-root}/dist'

emit:
  - '@typespec/openapi3'

options:
  '@typespec/openapi3':
    emitter-output-dir: '{output-dir}/openapi'
    output-file: '{service-name-if-multiple}.{file-type}'
    file-type: yaml
    omit-unreachable-types: true
